-- Phase 1: Roles (RBAC)
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DE_ENGINEER;

GRANT USAGE ON DATABASE RETAIL_DE_PROJECT TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE DE_WH_XS TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE DE_WH_M TO ROLE DE_ENGINEER;

GRANT ALL ON SCHEMA RETAIL_DE_PROJECT.RAW TO ROLE DE_ENGINEER;
GRANT ALL ON SCHEMA RETAIL_DE_PROJECT.STAGING TO ROLE DE_ENGINEER;
GRANT ALL ON SCHEMA RETAIL_DE_PROJECT.ANALYTICS TO ROLE DE_ENGINEER;

-- Replace <YOUR_USERNAME> with your actual Snowflake username
GRANT ROLE DE_ENGINEER TO USER <YOUR_USERNAME>;

-- Switch into least-privilege role for the rest of the project
USE ROLE DE_ENGINEER;
USE WAREHOUSE DE_WH_XS;
USE DATABASE RETAIL_DE_PROJECT;
