--  1: Resource monitor (cost guardrail)
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS DE_PROJECT_MONITOR
  WITH CREDIT_QUOTA = 10
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE DE_WH_XS SET RESOURCE_MONITOR = DE_PROJECT_MONITOR;
ALTER WAREHOUSE DE_WH_M SET RESOURCE_MONITOR = DE_PROJECT_MONITOR;
